### ISSUE TITLE
Lexical syntax error triggers an exception with message "Class does not exist"

### ISSUE THREAD

**Issue by Luc45** [lucatume/di52#25]
Due to a PHP limitation, when using `ReflectionClass` on a class that has a syntax error that prevents PHP from parsing it (as with lexical errors, unexpected tokens), it throws a `ReflectionException` saying that **The class does not exist**:

```
[27-Nov-2020 12:23:53 UTC] PHP Fatal error:  Uncaught RuntimeException: 'WPStaging\Pro\Snapshot\Ajax\Delete'
	 => 'WPStaging\Pro\Snapshot\Service'
	 => Error while making 'WPStaging\Pro\Snapshot\Site\Service\SnapshotService': Class WPStaging\Framework\Filesystem\Filesystem does not exist in /var/www/single/wp-content/plugins/wp-staging-dev/vendor/lucatume/di52/src/tad/DI52/Container.php:356
Stack trace:
#0 /var/www/single/wp-content/plugins/wp-staging-dev/vendor/lucatume/di52/src/tad/DI52/Container.php(281): tad_DI52_Container->resolve('WPStaging\\Pro\\S...')
#1 /var/www/single/wp-content/plugins/wp-staging-dev/Pro/Snapshot/SnapshotServiceProvider.php(35): tad_DI52_Container->make('WPStaging\\Pro\\S...')
#2 /var/www/single/wp-content/plugins/wp-staging-dev/Framework/DI/ServiceProvider.php(10): WPStaging\Pro\Snapshot\SnapshotServiceProvider->addHooks()
#3 /var/www/single/wp-content/plugins/wp-staging-dev/vendor/lucatume/di52/src/tad/DI52/Container.php(484): WPStaging\Framework\DI\ServiceProvider->register()
#4 /var/www/single/wp-content/plugins/wp-stagin in /var/www/single/wp-content/plugins/wp-staging-dev/vendor/lucatume/di52/src/tad/DI52/Container.php on line 356
```

In reality, the error was a missing semi-colon on the `WPStaging\Framework\Filesystem\Filesystem` class.

I suggest we try to improve this error message, saying something like `Could not reflect class XYZ. This class might have a syntax error, or might not exist.`

I can open a PR for this in the next couple of days.

**Comment by lucatume** [comment]
Handling that exception would be nice, but fatal errors can only be handled on PHP 7.
The handling should be conditional to PHP 7, else just bubble up the error.

**Comment by lucatume** [comment]
I will address this in #26
